dbt_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('account') }}"
      user: "{{ env_var('user') }}"
      password: "{{ env_var('password') }}"
      role: "{{ env_var('role', 'ACCOUNTADMIN') }}"
      warehouse: "{{ env_var('warehouse') }}"
      database: "{{ env_var('database') }}"
      schema: "{{ env_var('schema', 'PUBLIC') }}"
      threads: 4