dbt_poc:
  target: dev
  outputs:
    dev:
      type: redshift
      # host: "{{ env_var('REDSHIFT_HOST') }}"
      # user: "{{ env_var('REDSHIFT_USER') }}"
      # password: "{{ env_var('REDSHIFT_PASSWORD') }}"
      host : dbt-poc.ck74sbgav22w.eu-central-1.redshift.amazonaws.com
      user : akym-dev
      password : 97C_rikNxd9Xg5!
      port: 5439
      dbname: dev
      schema: "dbt_analytics"  # The schema where dbt will build your table
      threads: 4