name: CI pipeline

on:
  pull_request:
    paths:
      - "**.sql"
      - "dbt/models/**"
      - "dbt/dbt_project.yml"
      - "dbt/profiles.yml"
      - "requirements*.txt"
      - ".sqlfluff"

jobs:
  dbt-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt

      - name: Run SQLFluff lint
        run: sqlfluff lint dbt/models/